apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: woc-panel
  namespace: wechat-on-cloud
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: woc-panel
  namespace: wechat-on-cloud
subjects:
  - kind: ServiceAccount
    name: woc-panel
    namespace: wechat-on-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: woc-panel
